[build]
  command = "npm install --legacy-peer-deps && npx expo install @expo/webpack-config@^19.0.0 && npx expo export --platform web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 