[build]
  command = "npx expo export --platform web"
  publish = "dist"

[context.production.environment]
  # Optional: Set Node version if needed
  NODE_VERSION = "18"

[context.production]
  command = "npx expo export --platform web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
